### ISSUE TITLE
MuP/Fan-in initialization is used in GPT code

### ISSUE THREAD

**Issue by xidulu** [tml-epfl/why-weight-decay#1]
I noticed that the weight init for MLP and attention heads are normalized by n_embd/fan-in, different from the original NanoGPT code
https://github.com/tml-epfl/why-weight-decay/blob/main/large_language_models/model.py#L162

But this piece of code is not actually used in experiments right? custom_init seems to always be turned off in all config files.

**Comment by max-andr** [comment]
Right, it wasn't used in the experiments. I added this piece of code for some internal experiments that we didn't report in the paper.

**Comment by xidulu** [comment]
Thanks!
